name: pull_request labeled

on:
  # push:
  pull_request:
    types: [labeled]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - id: step1
        run: echo "::set-output name=test::job2/step1"
      - name: environment-variables
        run: |
          echo "CI                 : ${CI}"
          echo "GITHUB_WORKFLOW    : ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_ID      : ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER  : ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_ACTION      : ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS     : ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR       : ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY  : ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME  : ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH  : ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE   : ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA         : ${GITHUB_SHA}"
          echo "GITHUB_REF         : ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF    : ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF    : ${GITHUB_BASE_REF}"
          echo "GITHUB_SERVER_URL  : ${GITHUB_SERVER_URL}"
          echo "GITHUB_API_URL     : ${GITHUB_API_URL}"
          echo "GITHUB_GRAPHQL_URL : ${GITHUB_GRAPHQL_URL}"
      - name: env context
        run: |
          echo 'The "env" can not use in "run" keyword'
          echo "CI              (string) : ${{ env.CI }}"
          echo "GITHUB_WORKFLOW (string) : ${{ env.GITHUB_WORKFLOW }}"
          echo "GITHUB_RUN_ID   (string) : ${{ env.GITHUB_RUN_ID }}"
          echo "..."
      - name: github context
        run: |
          echo "github.action           (string) : ${{ github.action }}"
          echo "github.action_path      (string) : ${{ github.action_path }}"
          echo "github.actor            (string) : ${{ github.actor }}"
          echo "github.base_ref         (string) : ${{ github.base_ref }}"
          echo "github.event_name       (string) : ${{ github.event_name }}"
          echo "github.event_path       (string) : ${{ github.event_path }}"
          echo "github.head_ref         (string) : ${{ github.head_ref }}"
          echo "github.job              (string) : ${{ github.job }}"
          echo "github.ref              (string) : ${{ github.ref }}"
          echo "github.repository       (string) : ${{ github.repository }}"
          echo "github.repository_owner (string) : ${{ github.repository_owner }}"
          echo "github.run_id           (string) : ${{ github.run_id }}"
          echo "github.run_number       (string) : ${{ github.run_number }}"
          echo "github.sha              (string) : ${{ github.sha }}"
          echo "github.token            (string) : ${{ github.token }}"
          echo "github.workflow         (string) : ${{ github.workflow }}"
          echo "github.workspace        (string) : ${{ github.workspace }}"
      - name: github.event context
        run: |
          echo "github.event            (object) : ${{ toJSON(github.event) }}"
      - name: job context
        run: |
          echo "job.container.id       (string) : ${{ job.container.id }}"
          echo "job.container.network  (string) : ${{ job.container.network }}"
          echo "job.services           (object) : ${{ toJSON(job.services) }}"
          echo "job.status             (string) : ${{ job.status }}"
      - name: steps context
        run: |
          echo "steps (object) : ${{ toJSON(steps) }}"
      - name: runner context
        run: |
          echo "runner.os         (string) : ${{ runner.os }}"
          echo "runner.temp       (string) : ${{ runner.temp }}"
          echo "runner.tool_cache (string) : ${{ runner.tool_cache }}"
      - name: needs context
        run: |
          echo "needs (object) : ${{ toJSON(needs) }}"
      - name: literal
        run: |
          echo "null           : ${{ null }}"
          echo "boolean        : ${{ false }}"
          echo "integer        : ${{ 711 }}"
          echo "float          : ${{ -9.2 }}"
          echo "hex            : ${{ 0xff }}"
          # The workflow is not valid. .github/workflows/echo_env.yml (Line: 91, Col: 14): Unexpected symbol: '-2.99-e2'. Located at position 1 within expression: -2.99-e2
          # echo "exponential    : {{ -2.99-e2 }}"
          echo "string         : ${{ 'Mona the Octocat' }}"
          echo "escaped string : ${{ 'It''s open source!' }}"
