name: pull_request labeled bug

on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "github.event_name"
          echo "${{ toJSON(github.event_name) }}"
          echo "github.event.action"
          echo "${{ toJSON(github.event.action) }}"
          echo "github.event.pull_request.state"
          echo "${{ toJSON(github.event.pull_request.state) }}"
      - run: echo "labeled bug"
        if: |
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.state == 'open' &&
            contains(github.event.pull_request.labels.*.name, 'bug')
          )
