name: Schedule

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |-
          echo "Hello"
          date
