name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr_url = context.payload.pull_request.self
            const result = await github.request(pr_url)
            console.log(result)

      - name: dump event
        run: |
          mkdir -p artifacts
          cat <<EOD > artifacts/event_${{ github.event_name }}_${{ github.event.action }}.json
            ${{ toJSON(github.event) }}
          EOD
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifacts/
        if: always()
