name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |-
          echo "Hello"
          echo "github.workflow:${{ github.workflow }}"
          echo "GITHUB_WORKFLOW:${GITHUB_WORKFLOW}"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_ID:${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER:${GITHUB_RUN_NUMBER}"
          date
          sleep 10
          date
          sleep 10
          date
          sleep 10
          date
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check other running
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            async function existsActiveWorkflowRun(workflow_id) {
              // current workflow run
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const run_id = parseInt(process.env.GITHUB_RUN_ID, 10);
              const run_number = parseInt(process.env.GITHUB_RUN_NUMBER, 10);
              const result = await github.actions.listWorkflowRuns({ owner, repo, workflow_id });
              const { workflow_runs } = result.data;
              for (const run of workflow_runs) {
                if (run.id == run_id && run.run_number == run_number) {
                  continue;
                }
                if (run.status == 'in_progress') {
                  return true;
                }
              }
              return false;
            }

            const result = await existsActiveWorkflowRun('test.yml');
            console.log(`result:${result}`);
