name: Test

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name:
        id: current_labels
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: json
          script: |
            // console.log('-- pr --')
            // console.log(context.payload.pull_request)

            const pr_url = context.payload.pull_request._links.self.href
            console.log('-- pr_url --')
            console.log(pr_url)

            const result = await github.request(pr_url)
            // console.log('-- result --')
            // console.log(result)

            const labels = result.data.labels.map((v)=>v.name)
            console.log('-- labels --')
            console.log(labels)
            return labels

      - name: show current labels
        run: |
          cat <<EOD
            ${{ toJSON(steps.current_labels.outputs.result) }}
          EOD

      - name: dump event
        run: |
          mkdir -p artifacts
          cat <<EOD > artifacts/event_${{ github.event_name }}_${{ github.event.action }}.json
            ${{ toJSON(github.event) }}
          EOD
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifacts/
        if: always()
