name: Test

on:
  pull_request:
    paths:
      - README.md

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |-
          echo "Hello"
          date
