name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |-
          echo "Hello"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_ID:${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER:${GITHUB_RUN_NUMBER}"
          date
          sleep 20
          date
